"""Generate professional PDF reports for matches."""

import os
from datetime import datetime
from pathlib import Path
import matplotlib.pyplot as plt
import matplotlib.patches as mpatches
from fpdf import FPDF
import tempfile

from .pdf_style import apply_agelytics_style, COLORS, get_player_colors


class MatchPDF(FPDF):
    """Custom PDF class with header and footer."""
    
    def __init__(self, match_data, player_name=None):
        super().__init__()
        self.match_data = match_data
        self.player_name = player_name
        self.temp_images = []
        
    def header(self):
        """Page header with logo/title."""
        self.set_font('Helvetica', 'B', 24)
        self.set_text_color(44, 62, 80)  # text_primary
        self.cell(0, 10, 'AGELYTICS', 0, 1, 'L')
        
        self.set_font('Helvetica', '', 14)
        self.set_text_color(127, 140, 141)  # text_secondary
        self.cell(0, 6, 'Match Report', 0, 1, 'L')
        
        self.ln(5)
        
    def footer(self):
        """Page footer."""
        self.set_y(-15)
        self.set_font('Helvetica', 'I', 8)
        self.set_text_color(127, 140, 141)
        self.cell(0, 10, f'Generated by Agelytics - github.com/tiuitobot/agelytics - {datetime.now().strftime("%Y-%m-%d %H:%M")}', 0, 0, 'C')
        
    def add_separator(self):
        """Add a thin gray separator line."""
        self.set_draw_color(189, 195, 199)
        self.set_line_width(0.3)
        self.line(10, self.get_y(), 200, self.get_y())
        self.ln(5)
        
    def add_kpi_card(self, label, value, x, y, width=45, height=20, color=None):
        """Add a KPI card with large number and label."""
        self.set_xy(x, y)
        
        # Draw background (subtle)
        if color:
            self.set_fill_color(*color)
            self.rect(x, y, width, height, 'F')
        
        # Value (large)
        self.set_font('Helvetica', 'B', 18)
        self.set_text_color(44, 62, 80)
        self.set_xy(x, y + 5)
        self.cell(width, 8, str(value), 0, 0, 'C')
        
        # Label (small)
        self.set_font('Helvetica', '', 9)
        self.set_text_color(127, 140, 141)
        self.set_xy(x, y + 14)
        self.cell(width, 5, label, 0, 0, 'C')
        
    def add_section_title(self, title):
        """Add a section title."""
        self.ln(3)
        self.set_font('Helvetica', 'B', 14)
        self.set_text_color(44, 62, 80)
        self.cell(0, 8, title, 0, 1, 'L')
        self.ln(2)
        
    def add_text_block(self, text):
        """Add a text paragraph."""
        self.set_font('Helvetica', '', 10)
        self.set_text_color(44, 62, 80)
        self.multi_cell(0, 5, text)
        self.ln(2)
        
    def add_chart_image(self, img_path, width=180):
        """Add a chart image to the PDF."""
        x = (210 - width) / 2  # Center horizontally
        self.image(img_path, x=x, w=width)
        self.ln(5)
        self.temp_images.append(img_path)
        
    def cleanup(self):
        """Remove temporary image files."""
        for img in self.temp_images:
            try:
                os.unlink(img)
            except:
                pass


def format_time(seconds):
    """Format seconds as MM:SS."""
    mins = int(seconds // 60)
    secs = int(seconds % 60)
    return f"{mins:02d}:{secs:02d}"


def generate_age_up_chart(match):
    """Generate age-up timeline chart."""
    apply_agelytics_style()
    
    fig, ax = plt.subplots(figsize=(8, 4))
    
    age_ups = match.get('age_ups', [])
    if not age_ups:
        plt.close()
        return None
        
    # Group by player
    players = {}
    for up in age_ups:
        player = up['player']
        if player not in players:
            players[player] = {}
        players[player][up['age']] = up['timestamp_secs']
    
    ages = ['Feudal Age', 'Castle Age', 'Imperial Age']
    age_positions = {age: i for i, age in enumerate(ages)}
    
    colors = get_player_colors(len(players))
    y_offset = 0.2
    
    for idx, (player, player_ages) in enumerate(players.items()):
        y_values = []
        x_values = []
        
        for age in ages:
            if age in player_ages:
                y_values.append(age_positions[age] + (idx - 0.5) * y_offset)
                x_values.append(player_ages[age])
        
        if x_values:
            ax.barh(y_values, x_values, height=0.15, label=player, color=colors[idx])
    
    ax.set_yticks(list(age_positions.values()))
    ax.set_yticklabels(ages)
    ax.set_xlabel('Time (seconds)', fontsize=11)
    ax.set_title('Age-Up Timeline', fontsize=13, fontweight='bold', color=COLORS['text_primary'])
    ax.legend(loc='lower right')
    
    plt.tight_layout()
    
    # Save to temp file
    fd, path = tempfile.mkstemp(suffix='.png', prefix='agelytics_')
    os.close(fd)
    plt.savefig(path, dpi=150, bbox_inches='tight')
    plt.close()
    
    return path


def generate_tc_idle_chart(match, player_name=None):
    """Generate TC idle time by era chart."""
    apply_agelytics_style()
    
    fig, ax = plt.subplots(figsize=(8, 4))
    
    players = match.get('players', [])
    if not players:
        plt.close()
        return None
    
    # Extract TC idle by era (if available)
    eras = ['Dark', 'Feudal', 'Castle', 'Imperial']
    
    # For now, show total TC idle as we don't have per-era data in this match
    player_names = []
    tc_idle_values = []
    
    for p in players:
        player_names.append(p['name'])
        tc_idle_values.append(p.get('tc_idle_secs', 0) / 60)  # Convert to minutes
    
    colors = get_player_colors(len(players))
    bars = ax.bar(player_names, tc_idle_values, color=colors, width=0.6)
    
    # Highlight player's bar if specified
    if player_name:
        for i, name in enumerate(player_names):
            if name == player_name:
                bars[i].set_edgecolor(COLORS['accent_orange'])
                bars[i].set_linewidth(2.5)
    
    ax.set_ylabel('TC Idle Time (minutes)', fontsize=11)
    ax.set_title('Town Center Idle Time', fontsize=13, fontweight='bold', color=COLORS['text_primary'])
    ax.grid(axis='y', alpha=0.3)
    
    plt.tight_layout()
    
    fd, path = tempfile.mkstemp(suffix='.png', prefix='agelytics_')
    os.close(fd)
    plt.savefig(path, dpi=150, bbox_inches='tight')
    plt.close()
    
    return path


def generate_army_composition_chart(match):
    """Generate army composition horizontal bar chart."""
    apply_agelytics_style()
    
    unit_production = match.get('unit_production', {})
    if not unit_production:
        return None
    
    fig, ax = plt.subplots(figsize=(8, 5))
    
    # Combine all units, exclude villagers
    all_units = set()
    for player, units in unit_production.items():
        for unit in units.keys():
            if unit.lower() != 'villager':
                all_units.add(unit)
    
    if not all_units:
        plt.close()
        return None
    
    all_units = sorted(all_units)
    players = list(unit_production.keys())
    colors = get_player_colors(len(players))
    
    y_pos = 0
    spacing = 0.8
    bar_height = 0.35
    
    yticks = []
    ytick_labels = []
    
    for unit in all_units:
        yticks.append(y_pos)
        ytick_labels.append(unit)
        
        for idx, player in enumerate(players):
            count = unit_production[player].get(unit, 0)
            if count > 0:
                offset = idx * bar_height - bar_height * (len(players) - 1) / 2
                ax.barh(y_pos + offset, count, height=bar_height, 
                       label=player if unit == all_units[0] else "", 
                       color=colors[idx])
        
        y_pos += spacing
    
    ax.set_yticks(yticks)
    ax.set_yticklabels(ytick_labels)
    ax.set_xlabel('Unit Count', fontsize=11)
    ax.set_title('Army Composition', fontsize=13, fontweight='bold', color=COLORS['text_primary'])
    ax.legend(loc='lower right')
    ax.grid(axis='x', alpha=0.3)
    
    plt.tight_layout()
    
    fd, path = tempfile.mkstemp(suffix='.png', prefix='agelytics_')
    os.close(fd)
    plt.savefig(path, dpi=150, bbox_inches='tight')
    plt.close()
    
    return path


def generate_match_pdf(match, output_path, player_name=None):
    """Generate a complete match PDF report."""
    pdf = MatchPDF(match, player_name)
    pdf.add_page()
    
    # Match info line
    pdf.set_font('Helvetica', '', 10)
    pdf.set_text_color(127, 140, 141)
    played_at = match.get('played_at', 'Unknown')
    map_name = match.get('map_name', 'Unknown')
    duration = format_time(match.get('duration_secs', 0))
    pdf.cell(0, 6, f"Date: {played_at}  |  Map: {map_name}  |  Duration: {duration}", 0, 1, 'L')
    pdf.ln(5)
    
    # KPI Cards
    players = match.get('players', [])
    if len(players) >= 2:
        p1, p2 = players[0], players[1]
        
        # Determine focus player
        focus = p1 if player_name is None or p1['name'] == player_name else p2
        opponent = p2 if focus == p1 else p1
        
        # Result
        result_text = "VICTORY" if focus.get('winner') else "DEFEAT"
        result_color = (39, 174, 96) if focus.get('winner') else (231, 76, 60)
        pdf.add_kpi_card("Result", result_text, 10, pdf.get_y(), width=45, height=20, color=result_color)
        
        # Duration
        pdf.add_kpi_card("Duration", duration, 60, pdf.get_y() - 20, width=45, height=20)
        
        # ELO gap
        elo_gap = abs(p1.get('elo', 0) - p2.get('elo', 0))
        pdf.add_kpi_card("ELO Gap", f"+{elo_gap}", 110, pdf.get_y() - 20, width=45, height=20)
        
        # Opening
        opening = focus.get('opening_strategy', 'Unknown')
        pdf.add_kpi_card("Opening", opening if opening else "N/A", 160, pdf.get_y() - 20, width=45, height=20)
    
    pdf.ln(25)
    pdf.add_separator()
    
    # Section 1: Age-Up Timeline
    pdf.add_section_title("Age-Up Timeline")
    
    age_chart = generate_age_up_chart(match)
    if age_chart:
        pdf.add_chart_image(age_chart, width=170)
        
        # Add contextual text about age-ups
        age_ups = match.get('age_ups', [])
        if len(players) >= 2 and age_ups:
            p1, p2 = players[0], players[1]
            p1_feudal = next((a['timestamp_secs'] for a in age_ups if a['player'] == p1['name'] and a['age'] == 'Feudal Age'), None)
            p2_feudal = next((a['timestamp_secs'] for a in age_ups if a['player'] == p2['name'] and a['age'] == 'Feudal Age'), None)
            
            if p1_feudal and p2_feudal:
                feudal_diff = p1_feudal - p2_feudal
                faster_player = p1['name'] if feudal_diff < 0 else p2['name']
                text = f"{faster_player} reached Feudal Age {'ahead of' if feudal_diff < 0 else 'behind'} their opponent by {abs(feudal_diff):.0f} seconds ({format_time(abs(feudal_diff))})."
                pdf.add_text_block(text)
    
    pdf.add_separator()
    
    # Section 2: Economy
    pdf.add_section_title("Economy")
    
    tc_chart = generate_tc_idle_chart(match, player_name)
    if tc_chart:
        pdf.add_chart_image(tc_chart, width=170)
        
        # Add economy text
        if len(players) >= 2:
            p1 = players[0]
            vill_count = match.get('unit_production', {}).get(p1['name'], {}).get('Villager', 0)
            farm_gap = p1.get('farm_gap_average', 0)
            tc_idle = p1.get('tc_idle_secs', 0)
            
            text = f"With {vill_count} villagers produced and a farm gap of {farm_gap:.1f}s, {p1['name']} maintained a {'solid' if farm_gap < 5 else 'developing'} economy throughout the match."
            pdf.add_text_block(text)
            
            if 'tc_idle_dark' in p1 and p1['tc_idle_dark']:
                tc_idle_dark = p1['tc_idle_dark']
                text2 = f"TC idle time of {tc_idle_dark:.0f}s in Dark Age {'shows strong macro' if tc_idle_dark < 60 else 'suggests room for improvement in early game villager production'}."
                pdf.add_text_block(text2)
    
    pdf.add_separator()
    
    # Section 3: Military
    pdf.add_section_title("Military")
    
    army_chart = generate_army_composition_chart(match)
    if army_chart:
        pdf.add_chart_image(army_chart, width=170)
    
    # Opening strategy text
    if len(players) >= 2:
        for p in players:
            opening = p.get('opening_strategy')
            if opening:
                pdf.add_text_block(f"{p['name']} opened with a {opening} strategy.")
    
    pdf.add_separator()
    
    # Section 4: Buildings
    pdf.add_section_title("Buildings & Infrastructure")
    
    buildings = match.get('buildings', {})
    if buildings and len(players) >= 2:
        for p in players:
            player_buildings = buildings.get(p['name'], {})
            if player_buildings:
                key_buildings = ['Town Center', 'Castle', 'Barracks', 'Archery Range', 'Stable']
                building_text = f"{p['name']}: "
                building_parts = []
                for b in key_buildings:
                    if b in player_buildings:
                        building_parts.append(f"{player_buildings[b]} {b}")
                if building_parts:
                    building_text += ", ".join(building_parts)
                    pdf.add_text_block(building_text)
    
    # Save PDF
    pdf.output(output_path)
    pdf.cleanup()
    
    return output_path


if __name__ == "__main__":
    # Test with latest match
    from .db import get_db, get_last_match
    
    conn = get_db()
    match = get_last_match(conn)
    conn.close()
    
    if match:
        output = "reports/test_match_report.pdf"
        os.makedirs("reports", exist_ok=True)
        generate_match_pdf(match, output, player_name="blzulian")
        print(f"Generated: {output}")
    else:
        print("No match found in database")
