"""Generate professional PDF reports for player career statistics."""

import os
from datetime import datetime
import matplotlib.pyplot as plt
import matplotlib.dates as mdates
from fpdf import FPDF
import tempfile

from .pdf_style import apply_agelytics_style, COLORS, get_player_colors
from .db import get_db, get_player_stats


class StatsPDF(FPDF):
    """Custom PDF class for stats reports."""
    
    def __init__(self, player_name):
        super().__init__()
        self.player_name = player_name
        self.temp_images = []
        
    def header(self):
        """Page header."""
        self.set_font('Helvetica', 'B', 24)
        self.set_text_color(44, 62, 80)
        self.cell(0, 10, 'AGELYTICS', 0, 1, 'L')
        
        self.set_font('Helvetica', '', 14)
        self.set_text_color(127, 140, 141)
        self.cell(0, 6, f'Career Stats - {self.player_name}', 0, 1, 'L')
        
        self.ln(5)
        
    def footer(self):
        """Page footer."""
        self.set_y(-15)
        self.set_font('Helvetica', 'I', 8)
        self.set_text_color(127, 140, 141)
        self.cell(0, 10, f'Generated by Agelytics - github.com/tiuitobot/agelytics - {datetime.now().strftime("%Y-%m-%d %H:%M")}', 0, 0, 'C')
        
    def add_separator(self):
        """Add separator line."""
        self.set_draw_color(189, 195, 199)
        self.set_line_width(0.3)
        self.line(10, self.get_y(), 200, self.get_y())
        self.ln(5)
        
    def add_kpi_card(self, label, value, x, y, width=45, height=20):
        """Add KPI card."""
        self.set_xy(x, y)
        
        self.set_font('Helvetica', 'B', 18)
        self.set_text_color(44, 62, 80)
        self.set_xy(x, y + 5)
        self.cell(width, 8, str(value), 0, 0, 'C')
        
        self.set_font('Helvetica', '', 9)
        self.set_text_color(127, 140, 141)
        self.set_xy(x, y + 14)
        self.cell(width, 5, label, 0, 0, 'C')
        
    def add_section_title(self, title):
        """Add section title."""
        self.ln(3)
        self.set_font('Helvetica', 'B', 14)
        self.set_text_color(44, 62, 80)
        self.cell(0, 8, title, 0, 1, 'L')
        self.ln(2)
        
    def add_chart_image(self, img_path, width=180):
        """Add chart image."""
        x = (210 - width) / 2
        self.image(img_path, x=x, w=width)
        self.ln(5)
        self.temp_images.append(img_path)
        
    def cleanup(self):
        """Clean up temp files."""
        for img in self.temp_images:
            try:
                os.unlink(img)
            except:
                pass


def generate_elo_progression_chart(player_name, db_path=None):
    """Generate ELO progression line chart."""
    apply_agelytics_style()
    
    # Get match history with ELO
    conn = get_db(db_path)
    rows = conn.execute("""
        SELECT m.played_at, mp.elo
        FROM match_players mp
        JOIN matches m ON mp.match_id = m.id
        WHERE mp.name = ? AND mp.elo IS NOT NULL
        ORDER BY m.played_at ASC
    """, (player_name,)).fetchall()
    conn.close()
    
    if not rows:
        return None
    
    dates = []
    elos = []
    
    for row in rows:
        try:
            date = datetime.fromisoformat(row['played_at'].replace('Z', '+00:00'))
            dates.append(date)
            elos.append(row['elo'])
        except:
            continue
    
    if not dates:
        return None
    
    fig, ax = plt.subplots(figsize=(9, 4))
    
    ax.plot(dates, elos, color=COLORS['accent_orange'], linewidth=2.5, marker='o', markersize=4)
    ax.fill_between(dates, elos, alpha=0.2, color=COLORS['accent_orange'])
    
    ax.set_xlabel('Date', fontsize=11)
    ax.set_ylabel('ELO Rating', fontsize=11)
    ax.set_title('ELO Progression', fontsize=13, fontweight='bold', color=COLORS['text_primary'])
    
    # Format x-axis
    ax.xaxis.set_major_formatter(mdates.DateFormatter('%b %d'))
    fig.autofmt_xdate()
    
    ax.grid(alpha=0.3)
    
    plt.tight_layout()
    
    fd, path = tempfile.mkstemp(suffix='.png', prefix='agelytics_')
    os.close(fd)
    plt.savefig(path, dpi=150, bbox_inches='tight')
    plt.close()
    
    return path


def generate_winrate_by_civ_chart(stats):
    """Generate win rate by civilization chart."""
    apply_agelytics_style()
    
    civs_data = stats.get('civs', {})
    if not civs_data:
        return None
    
    # Convert to list and calculate win rates
    civ_list = []
    for civ_name, data in civs_data.items():
        played = data['played']
        won = data['won']
        win_rate = (won / played * 100) if played > 0 else 0
        civ_list.append({
            'name': civ_name,
            'played': played,
            'won': won,
            'win_rate': win_rate
        })
    
    # Sort by games played, top 10
    civ_list.sort(key=lambda x: x['played'], reverse=True)
    civ_list = civ_list[:10]
    
    if not civ_list:
        return None
    
    civ_names = [c['name'] for c in civ_list]
    win_rates = [c['win_rate'] for c in civ_list]
    games_played = [c['played'] for c in civ_list]
    
    fig, ax = plt.subplots(figsize=(8, 5))
    
    bars = ax.barh(civ_names, win_rates, color=COLORS['primary_blue'])
    
    # Add games played as text
    for i, (bar, games) in enumerate(zip(bars, games_played)):
        width = bar.get_width()
        ax.text(width + 1, bar.get_y() + bar.get_height()/2, 
               f'{games} games', va='center', fontsize=8, color=COLORS['text_secondary'])
    
    ax.set_xlabel('Win Rate (%)', fontsize=11)
    ax.set_title('Win Rate by Civilization (Top 10)', fontsize=13, fontweight='bold', color=COLORS['text_primary'])
    ax.set_xlim(0, 105)
    ax.grid(axis='x', alpha=0.3)
    
    plt.tight_layout()
    
    fd, path = tempfile.mkstemp(suffix='.png', prefix='agelytics_')
    os.close(fd)
    plt.savefig(path, dpi=150, bbox_inches='tight')
    plt.close()
    
    return path


def generate_winrate_by_map_chart(player_name, db_path=None):
    """Generate win rate by map chart."""
    apply_agelytics_style()
    
    # Query map stats
    conn = get_db(db_path)
    rows = conn.execute("""
        SELECT m.map_name,
               COUNT(*) as games,
               SUM(CASE WHEN mp.winner = 1 THEN 1 ELSE 0 END) as wins
        FROM match_players mp
        JOIN matches m ON mp.match_id = m.id
        WHERE mp.name = ?
        GROUP BY m.map_name
        ORDER BY games DESC
        LIMIT 8
    """, (player_name,)).fetchall()
    conn.close()
    
    if not rows:
        return None
    
    map_names = []
    win_rates = []
    games_played = []
    
    for row in rows:
        map_names.append(row['map_name'])
        games = row['games']
        wins = row['wins']
        win_rate = (wins / games * 100) if games > 0 else 0
        win_rates.append(win_rate)
        games_played.append(games)
    
    fig, ax = plt.subplots(figsize=(8, 4))
    
    bars = ax.barh(map_names, win_rates, color=COLORS['accent_orange'])
    
    for i, (bar, games) in enumerate(zip(bars, games_played)):
        width = bar.get_width()
        ax.text(width + 1, bar.get_y() + bar.get_height()/2, 
               f'{games} games', va='center', fontsize=8, color=COLORS['text_secondary'])
    
    ax.set_xlabel('Win Rate (%)', fontsize=11)
    ax.set_title('Win Rate by Map (Top 8)', fontsize=13, fontweight='bold', color=COLORS['text_primary'])
    ax.set_xlim(0, 105)
    ax.grid(axis='x', alpha=0.3)
    
    plt.tight_layout()
    
    fd, path = tempfile.mkstemp(suffix='.png', prefix='agelytics_')
    os.close(fd)
    plt.savefig(path, dpi=150, bbox_inches='tight')
    plt.close()
    
    return path


def generate_stats_pdf(player_name, output_path, db_path=None):
    """Generate career stats PDF."""
    conn = get_db(db_path)
    stats = get_player_stats(conn, player_name)
    
    # Get first and last game dates
    date_query = conn.execute("""
        SELECT MIN(m.played_at) as first_game, MAX(m.played_at) as last_game
        FROM match_players mp
        JOIN matches m ON mp.match_id = m.id
        WHERE mp.name = ?
    """, (player_name,)).fetchone()
    conn.close()
    
    if not stats or stats.get('matches', 0) == 0:
        raise ValueError(f"No stats found for player: {player_name}")
    
    pdf = StatsPDF(player_name)
    pdf.add_page()
    
    # Summary line
    pdf.set_font('Helvetica', '', 10)
    pdf.set_text_color(127, 140, 141)
    total = stats['matches']
    first_game = date_query['first_game'][:10] if date_query['first_game'] else 'N/A'
    last_game = date_query['last_game'][:10] if date_query['last_game'] else 'N/A'
    pdf.cell(0, 6, f"Total Games: {total}  |  Period: {first_game} to {last_game}", 0, 1, 'L')
    pdf.ln(5)
    
    # KPI Cards
    win_rate = stats.get('winrate', 0)
    avg_elo = stats.get('elo_current', 0) or 0
    
    # Best civ (most played)
    civs = stats.get('civs', {})
    best_civ_name = 'N/A'
    if civs:
        best_civ = max(civs.items(), key=lambda x: x[1]['played'])
        best_civ_name = best_civ[0]
    
    pdf.add_kpi_card("Win Rate", f"{win_rate:.1f}%", 10, pdf.get_y(), width=45)
    pdf.add_kpi_card("Current ELO", f"{avg_elo:.0f}", 60, pdf.get_y() - 20, width=45)
    pdf.add_kpi_card("Total Games", str(total), 110, pdf.get_y() - 20, width=45)
    pdf.add_kpi_card("Most Played", best_civ_name, 160, pdf.get_y() - 20, width=45)
    
    pdf.ln(25)
    pdf.add_separator()
    
    # ELO Progression
    pdf.add_section_title("ELO Progression")
    elo_chart = generate_elo_progression_chart(player_name, db_path)
    if elo_chart:
        pdf.add_chart_image(elo_chart, width=175)
    
    pdf.add_separator()
    
    # Win Rate by Civ
    pdf.add_section_title("Win Rate by Civilization")
    civ_chart = generate_winrate_by_civ_chart(stats)
    if civ_chart:
        pdf.add_chart_image(civ_chart, width=170)
    
    pdf.add_separator()
    
    # Win Rate by Map
    pdf.add_section_title("Win Rate by Map")
    map_chart = generate_winrate_by_map_chart(player_name, db_path)
    if map_chart:
        pdf.add_chart_image(map_chart, width=170)
    
    # Save
    pdf.output(output_path)
    pdf.cleanup()
    
    return output_path


if __name__ == "__main__":
    # Test
    output = "reports/test_stats_report.pdf"
    os.makedirs("reports", exist_ok=True)
    generate_stats_pdf("blzulian", output)
    print(f"Generated: {output}")
